[build]
  command = "mkdir -p dist && echo 'Redirecting' > dist/index.html"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "https://www.axle-finance.com/hostadmin"
  status = 301
  force = true
